### ISSUE TITLE
Команда /releases

### ISSUE THREAD

**Issue by deman4ik** [CITKParus/CITK-Parus-Bot#10]
Отображает список последних релизов с ссылками на скачивание в обратном хронологическом порядке

Предлагаю хранить список релизов в json файле в данном репозитории и делать get запрос к данному файлу https://github.com/CITKParus/CITK-Parus-Bot/blob/master/PARUS8RELEASES.json

структуру предлагаю такую
{
"version": "8.5.6.1",
"release": "05.09.2017",
"url":"http://cloud.mail.ru/...",
"desc":"Добавлен новый сервис TaxRegisters"
}

**Comment by Mimyatina** [comment]
Реализовано. Но сделал на доп. словарях - см. словарь "Релизы" в "Прожекторе"
