### ISSUE TITLE
команда prjstate

### ISSUE THREAD

**Issue by megamozg** [CITKParus/CITK-Parus-Bot#3]
Ну куда ж без этого: по коду проекта выдать кол-во дней по договору, кол-во по плану, кол-во по факту, кол-во по исполнениям. Код проекта у нас русскими буквами в базе и может содержать слэши, тире и по-моем даже пробелы, так что надо наверное в кавычки брать или пробовать сначала так, если не найдено то в кавычках. Ну в общем подумать тут.

**Comment by Mimyatina** [comment]
Сейчас не понял тебя... Нигде в боте код проекта руками вводить не надо - строго по кнопкам тыкать... Когда ты по кнопке тыкаешь (с именем проекта, работы и т.п.) на сервер улетает рег. номер... В чём проблема? На самой кнопке кавычки писать - мне жалко места, его и так не много в мессенджере.

**Comment by megamozg** [comment]
мне кажется лучше было бы не выбирать и листать список, а сразу писать типа /prjstate suek

Но тут может быть наверное проблема, то что коды проектов у всех длинные и содержат пробелы. А может и нет. Это я предположил просто.

И в отличие от твоей текущей команды я бы выдавал только самые востребованные атрибуты - состояние трудоемкости и может плановую дату окончания и все.

**Comment by Mimyatina** [comment]
Добро. Спасибо Лёха. Но мое мнение - никто не помнит кодов своих проектов. А руководству надо помнить коды всех проектов. А исполнителям - всех куда они включены, и завтра их могут подключить к каким-то другим проектам... Список кнопок, где виден перечень доступных тебе  проектов видится лучшим решением на текущий момент. Пока закрываю.
